version: '3'
services:
  redis:
    image: redis:alpine
    volumes:
    - ./data/redis:/data
  celery:
    build: .
    command: "celery -A app.celery worker --loglevel=info"
    volumes:
    - ./litourgiya/:/litourgiya/
    depends_on:
    - redis
  backend:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./litourgiya/:/litourgiya/
    depends_on:
      - redis
      - celery
